version: '3'

networks:
  amplicode-addons-demo-r2-net:
    driver: bridge

services:
  amplicode-addons-demo-r2-postgres-12:
    container_name: amplicode-addons-demo-r2-postgres-12
    image: postgres:12
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${DB1_PASSWORD}
      POSTGRES_USER: ${DB1_USERNAME}
      POSTGRES_DB: ${DB1_NAME}
    networks:
      - amplicode-addons-demo-r2-net

  amplicode-addons-demo-r2:
    container_name: amplicode-addons-demo-r2
    image: docker.haulmont.com/platform/infrastructure/demo-cuba-apps-docker/demo-r2/amplicode-addons-demo-r2:full
    restart: unless-stopped
    environment:
      RDS_HOSTNAME: amplicode-addons-demo-r2-postgres-12
      RDS_PASSWORD: ${DB1_PASSWORD}
      RDS_USERNAME: ${DB1_USERNAME}
      RDS_DB_NAME: ${DB1_NAME}
      RDS_PORT: 5432
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8085:8080"
    networks:
      - amplicode-addons-demo-r2-net