CREATE TABLE salesperson
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255)                            NOT NULL,
    location     VARCHAR(255),
    phone        VARCHAR(255),
    territory_id BIGINT,
    CONSTRAINT pk_salesperson PRIMARY KEY (id)
);

ALTER TABLE salesperson
    ADD CONSTRAINT FK_SALESPERSON_ON_TERRITORY FOREIGN KEY (territory_id) REFERENCES territory (id);

INSERT INTO salesperson (id, name, phone, location, territory_id)
VALUES (8, 'Jon Snow', '555-2234123', 'POINT (-75.3662109375 38.993572058209466)', 3);

INSERT INTO salesperson (id, name, phone, location, territory_id)
VALUES (9, 'Jack Black', '444-234114', 'POINT (-82.52929687500001 31.728167146023935)', 4);

INSERT INTO salesperson (id, name, phone, location, territory_id)
VALUES (10, 'Homer Simpson', '3321413241', 'POINT (-89.82421875000001 39.8928799002948)', 5);

INSERT INTO salesperson (id, name, phone, location, territory_id)
VALUES (11, 'Marge Simpson', '555-234214', 'POINT (-93.77929687500001 32.54681317351517)', 6);