CREATE TABLE customer_order
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    amount         INTEGER,
    location       VARCHAR(255),
    salesperson_id BIGINT,
    CONSTRAINT pk_order PRIMARY KEY (id)
);

ALTER TABLE customer_order
    ADD CONSTRAINT FK_ORDER_ON_SALESPERSON FOREIGN KEY (salesperson_id) REFERENCES salesperson (id);

INSERT INTO customer_order (id, amount, location, salesperson_id)
values (12, 77.0, 'POINT (-89.593506 40.697299)', 10);

INSERT INTO customer_order (id, amount, location, salesperson_id)
values (13, 76.0, 'POINT (-90.703125 29.38217507514529)', 11);

INSERT INTO customer_order (id, amount, location, salesperson_id)
values (14, 75.0, 'POINT (-92.493896 31.278551)', 11);

INSERT INTO customer_order (id, amount, location, salesperson_id)
values (15, 55.0, 'POINT (-90.19775390625001 38.60828592850559)', 10);

INSERT INTO customer_order (id, amount, location, salesperson_id)
values (16, 54.0, 'POINT (-92.548828125 30.751277776257812)', 11);

INSERT INTO customer_order (id, amount, location, salesperson_id)
values (17, 44.0, 'POINT (-81.25488281250001 31.728167146023935)', 9);

INSERT INTO customer_order (id, amount, location, salesperson_id)
values (18, 32.0, 'POINT (-75.454102 38.61687)', 8);

INSERT INTO customer_order (id, amount, location, salesperson_id)
values (19, 28.0, 'POINT (-83.67187500000001 30.37287518811804)', 9);

INSERT INTO customer_order (id, amount, location, salesperson_id)
values (20, 27.0, 'POINT (-83.60595703125001 32.80574473290688)', 9);

INSERT INTO customer_order (id, amount, location, salesperson_id)
values (21, 13.0, 'POINT (-84.33105468750001 33.687781758439364)', 9);